In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
categories=os.listdir('C:/Users/hp/Face mask recognition/dataset')
categories

['with mask', 'without mask']

# data processing

In [3]:
image=[]
label=[]
for category in categories:
    img_path=os.path.join('C:/Users/hp/Face mask recognition/dataset',category)
    images=os.listdir(img_path)
    
    for img in images:
        data=cv2.imread(os.path.join(img_path,img))
        #0img=cv2.cvtColor(data,cv2.COLOR_BGR2GRAY)
        img_resized=cv2.resize(data,(100,100))
        image.append(img_resized)
        label.append(categories.index(category))
np.array(label)      

array([0, 0, 0, ..., 1, 1, 1])

In [4]:
image[0].shape

(100, 100, 3)

In [5]:
images=np.reshape(image,(len(image),100,100,3))      # Reshaping image size and converting in array
images.shape

(1376, 100, 100, 3)

In [6]:
labels=np.reshape(label,(len(label),))
labels.shape

(1376,)

In [7]:
labels

array([0, 0, 0, ..., 1, 1, 1])

In [8]:
from sklearn.utils import shuffle

images,labels=shuffle(images,labels)            # shuffling data

# spliting training and testing data

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test=train_test_split(images,labels,test_size=0.2,random_state=42)

In [11]:
X_train.shape

(1100, 100, 100, 3)

In [12]:
from keras.utils import to_categorical

y_train=to_categorical(y_train)
y_test=to_categorical(y_test)
y_test

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.

# Convolutional Neural Network Model

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,BatchNormalization,Dense,Dropout,Input,Flatten

In [14]:
model=Sequential()

model.add(Input(shape=(100,100,3)))

model.add(Conv2D(100,3,activation='relu',padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.5))

model.add(Conv2D(200,3,activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(2,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 100, 100, 100)     2800      
_________________________________________________________________
batch_normalization (BatchNo (None, 100, 100, 100)     400       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 50, 50, 100)       0         
_________________________________________________________________
dropout (Dropout)            (None, 50, 50, 100)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 48, 48, 200)       180200    
_________________________________________________________________
batch_normalization_1 (Batch (None, 48, 48, 200)       800       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 24, 24, 200)       0

# Training the model

In [15]:
from keras.callbacks import ModelCheckpoint

In [16]:
checkpoint=ModelCheckpoint('model-{epoch:03d}.model',monitor='val_accuracy',save_best_only=True)   # callback for model evaluation

In [17]:
history=model.fit(X_train,y_train,epochs=30,validation_split=0.1,verbose=1,callbacks=[checkpoint])

Epoch 1/30
31/31 [==============================] - ETA: 0s - loss: 3.9978 - accuracy: 0.7949WARNING:tensorflow:From C:\Users\hp\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: model-001.model\assets
31/31 [==============================] - 58s 2s/step - loss: 3.9978 - accuracy: 0.7949 - val_loss: 4.1769 - val_accuracy: 0.7182
Epoch 2/30
31/31 [==============================] - 59s 2s/step - loss: 0.2581 - accuracy: 0.9535 - val_loss: 0.7388 - val_accuracy: 0.9182
Epoch 3/30
31/31 [==============================] - 60s 2s/step - loss: 0.0506 - accuracy: 0.9879 - val_loss: 0.4720 - val_accuracy: 0.9273
Epoch 4/30
31/31 [==============================] - 65s 2s/step 

In [18]:
_,accuracy=model.evaluate(X_test,y_test)

9/9 [==============================] - 2s 180ms/step - loss: 3.2264 - accuracy: 0.8406


In [26]:
pred=model.predict(X_test)
pred

array([[1.00000000e+00, 3.83280277e-32],
       [1.00000000e+00, 2.73298788e-12],
       [1.00000000e+00, 9.60734335e-22],
       [1.00000000e+00, 4.39532149e-31],
       [2.71342222e-38, 1.00000000e+00],
       [1.00000000e+00, 2.19930713e-24],
       [8.10622712e-22, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 5.77490575e-28],
       [1.00000000e+00, 7.71567575e-24],
       [0.00000000e+00, 1.00000000e+00],
       [4.07396001e-04, 9.99592602e-01],
       [2.59877445e-30, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.82796711e-08],
       [1.00000000e+00, 3.34386601e-28],
       [2.46667138e-16, 1.00000000e+00],
       [2.49171885e-35, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [7.96129410e-32, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [3.71068889e-24, 1.00000000e+00],
       [1.64341870e-07, 9.99999881e-01],
       [8.727826

In [30]:
np.argmax(pred[45])

1

In [19]:
from keras.models import load_model

In [20]:
model=load_model('model-009.model')

# Detection of face mask

In [21]:
face_detection=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')    

In [25]:
labels_dict={0:'WITH MASK',1:'WITHOUT MASK'}
def mask_detection(img):
    
    faces=face_detection.detectMultiScale(img)
    for (x,y,w,h) in faces:
        face_img=img[y:y+h,x:x+w]                 # cutting face image from the frame      
        face_img=cv2.resize(face_img,(100,100))
        face_img=np.reshape(face_img,(1,100,100,3))
        predict=model.predict(face_img)
        
        if np.argmax(predict[0])==0:
            cv2.rectangle(img,(x,y),(x+w,y+h),color=(0,255,0),thickness=2)
            cv2.putText(img, labels_dict[0], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)
        elif np.argmax(predict[0])==1:
            cv2.rectangle(img,(x,y),(x+w,y+h),color=(0,0,255),thickness=2)
            cv2.putText(img, labels_dict[1], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)
    return faces

In [29]:
cap=cv2.VideoCapture(0)

while True:
    ret,frame=cap.read()

    mask_detection(frame)
    
    cv2.imshow('Live Video Mask Detection',frame)
    
    if cv2.waitKey(3)==27:
        break
        
cap.release()
cv2.destroyAllWindows()